name: Tests

on: ['push']

jobs:
  test:
    name: 'Unit Tests'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v2

      - name: Setup NodeJS
        uses: actions/setup-node@v2
        with:
          node-version: v18

      - name: Install npm dependencies
        run: npm install

      - name: Lint source code
        run: npm run lint

      - name: Run unit tests
        run: npm test
